plugins {
    id 'fabric-loom' version "${fabric_loom_version}"
    id 'maven-publish'
}

sourceCompatibility = JavaLanguageVersion.of(java_version as int)
targetCompatibility = JavaLanguageVersion.of(java_version as int)

archivesBaseName = "mcef-addon"
version = mod_version
group = "com.cinemamod"

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
    mavenLocal()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

    // Fabric API
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // MCEF Dependency (via includeBuild)
    modImplementation "com.cinemamod:mcef-fabric:2.1.6-1.21.4"
    // Also need common for the interfaces
    implementation "com.cinemamod:mcef:2.1.6-1.21.4"
}

loom {
    mixin {
        defaultRefmapName = "mcef-addon.refmap.json"
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", "${minecraft_version}"
    inputs.property "loader_version", "${fabric_loader_version}"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": "${minecraft_version}",
                "loader_version": "${fabric_loader_version}"
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = java_version as int
}

java {
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}
